quarkus:
  datasource:
    db-kind: postgresql
    devservices:
      enabled: true
      port: 5432
      image-name: postgres:15.4
      db-name: cryptography_test
      username: postgres
      password: postgres

  hibernate-orm:
    database:
      generation: drop-and-create

  flyway:
    default-schema: example
    migrate-at-start: true
    locations: db/migration,incept5/cryptography

# incept5 specific
incept5:
  cryptography:
    encryption:
      key:
        id: 81b4f837-c134-4e7f-bb5e-802d5dcc5d4c
        aes: 8hV/a1MfXxjS54JS+35TMQx7K2TH/8eX6BtrwRKXARg=
        hmac: sHjLLmW3wA6KWu3cBDJwi9bsVD7bqoTVEzJHacgSfns=
      decryption-keys:
        - id: ${incept5.cryptography.encryption.key.id}
          aes: ${incept5.cryptography.encryption.key.aes}
          hmac: ${incept5.cryptography.encryption.key.hmac}
