version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0
  python: circleci/python@2.1.1

jobs:
  python-tests:
    docker:
      - image: cimg/python:3.9
      - image: cimg/postgres:15.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cryptography_test
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          packages:
            - psycopg2-binary
            - cryptography
            - pyyaml
      - run:
          name: Run Python Unit Tests
          command: |
            cd scripts
            python -m unittest test_key_rotation.py
      - run:
          name: Run Python Integration Tests
          command: |
            cd scripts
            python -m unittest test_key_rotation_integration.py
          
  build-and-test:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Setup TestContainers
          command: |
            mkdir -p ~/.testcontainers
            echo "testcontainers.reuse.enable=true" > ~/.testcontainers.properties
      - gradle/with_cache:
          steps:
            - run:
                name: Build and Test
                command: ./gradlew clean build
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports
          destination: reports

  publish-to-jitpack:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Setup TestContainers
          command: |
            mkdir -p ~/.testcontainers
            echo "testcontainers.reuse.enable=true" > ~/.testcontainers.properties
      - run:
          name: Set Build Number
          command: |
            # Use the CircleCI build number directly without additional processing
            echo "export BUILD_NUMBER=${CIRCLE_BUILD_NUM}" >> $BASH_ENV
            source $BASH_ENV
            echo "Using build number: ${BUILD_NUMBER}"
      - gradle/with_cache:
          steps:
            - run:
                name: Build with Build Number
                command: |
                  echo "Using build number: ${BUILD_NUMBER}"
                  ./gradlew clean build -Pversion=1.0.${BUILD_NUMBER}
            - run:
                name: Publish to Local Maven Repository
                command: |
                  echo "Publishing with version: 1.0.${BUILD_NUMBER}"
                  ./gradlew publishToMavenLocal -Pversion=1.0.${BUILD_NUMBER}
      - run:
          name: Create and Push Git Tag
          command: |
            # Create a git tag with the version number
            VERSION="1.0.${BUILD_NUMBER}"
            echo "Creating tag for version: ${VERSION}"
            git config user.email "ci@incept5.com"
            git config user.name "CircleCI"
            
            # Check if tag already exists
            if git rev-parse "${VERSION}" >/dev/null 2>&1; then
              echo "Tag ${VERSION} already exists, skipping tag creation"
            else
              echo "Creating new tag ${VERSION}"
              git tag -a "${VERSION}" -m "Release version ${VERSION}"
              git push origin "${VERSION}"
            fi
      - run:
          name: Trigger JitPack Build
          command: |
            VERSION="1.0.${BUILD_NUMBER}"
            
            # Debug information
            echo "Maven repository location: $HOME/.m2/repository"
            echo "Using version: ${VERSION}"
            
            # List all artifacts in the local Maven repository
            echo "All artifacts in Maven repository:"
            find $HOME/.m2/repository/com/github/incept5 -type f -name "*.jar" | sort
            
            # Verify that both JARs exist locally
            if [ ! -f "$HOME/.m2/repository/com/github/incept5/cryptography-core/${VERSION}/cryptography-core-${VERSION}.jar" ]; then
              echo "ERROR: cryptography-core JAR not found locally at expected path"
              echo "Expected: $HOME/.m2/repository/com/github/incept5/cryptography-core/${VERSION}/cryptography-core-${VERSION}.jar"
              
              # Check if the directory exists
              if [ -d "$HOME/.m2/repository/com/github/incept5/cryptography-core" ]; then
                echo "Available versions for cryptography-core:"
                ls -la "$HOME/.m2/repository/com/github/incept5/cryptography-core/"
              fi
              
              # Try to find it elsewhere
              echo "Searching for cryptography-core JAR:"
              find $HOME/.m2/repository -name "cryptography-core-*.jar" | sort
              
              # Try one more publish with explicit version
              echo "Attempting one more publish with explicit version ${VERSION}"
              ./gradlew :cryptography-core:clean :cryptography-core:build :cryptography-core:publishToMavenLocal -Pversion=${VERSION} --stacktrace
              
              # Check again
              if [ -f "$HOME/.m2/repository/com/github/incept5/cryptography-core/${VERSION}/cryptography-core-${VERSION}.jar" ]; then
                echo "Successfully published cryptography-core JAR after retry"
              else
                echo "Failed to publish cryptography-core JAR after retry"
                exit 1
              fi
            fi
            
            if [ ! -f "$HOME/.m2/repository/com/github/incept5/cryptography-quarkus/${VERSION}/cryptography-quarkus-${VERSION}.jar" ]; then
              echo "ERROR: cryptography-quarkus JAR not found locally at expected path"
              echo "Expected: $HOME/.m2/repository/com/github/incept5/cryptography-quarkus/${VERSION}/cryptography-quarkus-${VERSION}.jar"
              
              # Check if the directory exists
              if [ -d "$HOME/.m2/repository/com/github/incept5/cryptography-quarkus" ]; then
                echo "Available versions for cryptography-quarkus:"
                ls -la "$HOME/.m2/repository/com/github/incept5/cryptography-quarkus/"
              fi
              
              # Try to find it elsewhere
              echo "Searching for cryptography-quarkus JAR:"
              find $HOME/.m2/repository -name "cryptography-quarkus-*.jar" | sort
              
              # Try one more publish with explicit version
              echo "Attempting one more publish with explicit version ${VERSION}"
              ./gradlew :cryptography-quarkus:clean :cryptography-quarkus:build :cryptography-quarkus:publishToMavenLocal -Pversion=${VERSION} --stacktrace
              
              # Check again
              if [ -f "$HOME/.m2/repository/com/github/incept5/cryptography-quarkus/${VERSION}/cryptography-quarkus-${VERSION}.jar" ]; then
                echo "Successfully published cryptography-quarkus JAR after retry"
              else
                echo "Failed to publish cryptography-quarkus JAR after retry"
                exit 1
              fi
            fi
            
            echo "Both artifacts verified locally"
            
            # Trigger JitPack build by making a request to the JitPack URL with the version tag
            echo "Triggering JitPack build for version ${VERSION}"
            # Trigger the root project build on JitPack
            curl -s "https://jitpack.io/com/github/incept5/cryptography-lib/${VERSION}/cryptography-lib-${VERSION}.pom" || true
            
            echo "JitPack build triggered for version ${VERSION}"
            echo "Root project will be available at: https://jitpack.io/#incept5/cryptography-lib/${VERSION}"
            echo "Modules will be available at:"
            echo "- https://jitpack.io/#incept5/cryptography-lib/cryptography-core/${VERSION}"
            echo "- https://jitpack.io/#incept5/cryptography-lib/cryptography-quarkus/${VERSION}"
            
            # Wait for JitPack to process the build
            echo "Waiting for JitPack to process the build..."
            sleep 180  # Increased wait time to allow JitPack to process
            
            # Verify the build status for the root project
            ROOT_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://jitpack.io/com/github/incept5/cryptography-lib/${VERSION}/cryptography-lib-${VERSION}.pom")
            if [ "$ROOT_STATUS" -eq 200 ]; then
              echo "Root project successfully published to JitPack!"
            else
              echo "Root project not found on JitPack. Status code: $ROOT_STATUS"
              echo "Check status at: https://jitpack.io/#incept5/cryptography-lib/${VERSION}"
            fi
            
            # Verify the build status for cryptography-core module
            CORE_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://jitpack.io/com/github/incept5/cryptography-lib/cryptography-core/${VERSION}/cryptography-core-${VERSION}.jar")
            if [ "$CORE_STATUS" -eq 200 ]; then
              echo "cryptography-core artifact successfully published to JitPack!"
            else
              echo "cryptography-core artifact not found on JitPack. Status code: $CORE_STATUS"
              echo "Check status at: https://jitpack.io/#incept5/cryptography-lib/${VERSION}"
            fi
            
            # Verify the build status for cryptography-quarkus module
            QUARKUS_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://jitpack.io/com/github/incept5/cryptography-lib/cryptography-quarkus/${VERSION}/cryptography-quarkus-${VERSION}.jar")
            if [ "$QUARKUS_STATUS" -eq 200 ]; then
              echo "cryptography-quarkus artifact successfully published to JitPack!"
            else
              echo "cryptography-quarkus artifact not found on JitPack. Status code: $QUARKUS_STATUS"
              echo "Check status at: https://jitpack.io/#incept5/cryptography-lib/${VERSION}"
            fi
            
            # Final verification
            if [ "$ROOT_STATUS" -eq 200 ] && [ "$CORE_STATUS" -eq 200 ] && [ "$QUARKUS_STATUS" -eq 200 ]; then
              echo "All artifacts successfully published to JitPack!"
            else
              echo "WARNING: One or more artifacts may not be available yet on JitPack."
              echo "This is normal as JitPack may take some time to process the build."
              echo ""
              echo "To use these artifacts in your project:"
              echo "1. Add the JitPack repository to your build file"
              echo "   repositories {"
              echo "     maven { url 'https://jitpack.io' }"
              echo "   }"
              echo ""
              echo "2. Add the dependencies"
              echo "   dependencies {"
              echo "     implementation 'com.github.incept5.cryptography-lib:cryptography-core:${VERSION}'"
              echo "     implementation 'com.github.incept5.cryptography-lib:cryptography-quarkus:${VERSION}'"
              echo "   }"
              echo ""
              echo "3. Or use the root project (includes all modules)"
              echo "   dependencies {"
              echo "     implementation 'com.github.incept5:cryptography-lib:${VERSION}'"
              echo "   }"
            fi

workflows:
  version: 2
  build-test-publish:
    jobs:
      - python-tests
      - build-and-test
      - publish-to-jitpack:
          requires:
            - build-and-test
            - python-tests
          filters:
            branches:
              only: main
